name: Deploy to Staging

on:
  push:
    branches: [ staging ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DIR_NAME: asta-wp-2024

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            tag_suffix: amd64
          - platform: linux/arm64
            tag_suffix: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set lowercase image name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and use buildx builder with docker-container driver
        run: |
          docker buildx create --name mybuilder --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-${{ matrix.tag_suffix }}
          platforms: ${{ matrix.platform }}
          builder: mybuilder
